version: '3'

services:
  php:
    image: php:5.6-apache
    container_name: php56-container
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"
    
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chall1
      MYSQL_USER: user1
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: